// outOfScope/svelte/src/App.svelte
<script>
  import Clock from "./Components/Clock.svelte";
  import Weather from './Components/Weather.svelte';
  import Alarms from './Components/Alarms.svelte';
</script>

<style global>
  @tailwind base;
  @tailwind components;
  @tailwind utilities;
</style>

<main>
  <div class="w-screen h-screen flex flex-wrap bg-gray-900 text-white">
    <div class="w-full md:w-1/2">
      <Clock />
    </div>
    <div class="w-full md:w-1/2 flex flex-col">
      <div class="h-full">
        <Weather />
      </div>
      <div class="h-full">
        <Alarms />
      </div>
    </div>
  </div>
</main>

// vue/src/App.vue
<template>
  <div id="app">
    <main>
      <div class="w-screen h-screen flex flex-wrap bg-gray-900 text-white">
        <div class="w-full md:w-1/2">
          <Clock />
        </div>
        <div class="w-full md:w-1/2 flex flex-col">
          <div class="h-full">
            <Weather />
          </div>
          <div class="h-full">
            <Alarms />
          </div>
        </div>
      </div>
    </main>
  </div>
</template>

<script>
import Clock from "./components/Clock.vue";
import Alarms from './components/Alarms.vue';
import Weather from './components/Weather.vue';

export default {
  name: "App",
  components: {
    Clock,
    Alarms,
    Weather
  },
};
</script>

<style>

</style>
